<?php

$crawler_fields = array(
    "AD_Site",
    "AD_Title",
    "AD_Section",
    "AD_KEY",
    "Ad_Link",
    "AD_Phone1",
    "AD_Phone2",
    "AD_ContactName1",
    "AD_ContactName2",
    "AD_ContactEmail",
    "AD_UpdateDate",
    "AD_Region",
    "AD_Area",
    "AD_City",
    "AD_Address",
    "AD_Price",
    "AD_Notes",
    "AD_ContactLink",
    "app_MoveInDate",
    "app_Neighborhood",
    "app_meter",
    "app_PropertyTypeIndex",
    "app_Typeindex",
    "app_Rooms",
    "app_BathRooms",
    "app_Floor",
    "app_FloorTotal",
    "app_Furniture",
    "app_FurnitureIndex",
    "app_FlatMatesCount",
    "app_RequiredGenderIndex",
    "app_BarsIndex",
    "app_LiftIndex",
    "app_AirConIndex",
    "app_storeroom",
    "app_ParkingIndex",
    "app_BalconyIndex",
    "app_BalconeCount",
    "app_SmokingIndex",
    "app_RenovatedIndex",
    "app_AirDirection",
    "app_Status",
    "app_RentTime",
    "app_Partners",
    "app_PartnerSex",
    "app_Animal",
    "app_handicapped",
    "app_SunBalcone",
    "app_ExtendOption",
    "car_Maker",
    "car_Model",
    "car_SubModel",
    "car_Color",
    "car_Engine",
    "car_Hand",
    "car_Year",
    "car_gear",
    "car_owner",
    "car_PreviousOwner",
    "car_Doors",
    "car_km",
    "car_Addition",
    "car_AirCon",
    "car_Volume",
    "car_AcceptTrade",
    "car_ElectricWindows",
    "car_GPS",
    "car_DVD",
    "car_ABS",
    "car_Sunroof",
    "car_Airbags",
    "car_AlloyWheels",
    "yad2_Category",
    "yad2_Product",
    "yad2_NameProduct",
    "yad2_SubCategory",
    "yad2_Maker",
    "Yad2_Status",
    "Yad2_AcceptTrade",
    "anim_Age",
    "anim_Gender",
    "anim_Breed",
    "AD_md5"
);

$production_fields = array(
    "POST_ID",
    "cDate",
    "uDate",
    "fDate",
    "dDate",
    "eDate",
    "AD_Site",
    "AD_Title",
    "AD_Section",
    "AD_KEY",
    "AD_Status",
    "AD_UserId",
    "AD_Random",
    "Ad_Link",
    "pictureHave",
    "pictureFromIcar",
    "PicturesString",
    "videoHave",
    "AD_Phone1",
    "AD_Phone2",
    "AD_ContactName1",
    "AD_ContactEmail",
    "AD_ContactCity",
    "AD_ContactName2",
    "AD_ContactLink",
    "Ad_Fax",
    "AD_WebSite",
    "AD_ContactAddress",
    "AD_PostDate",
    "AD_UpdateDate",
    "AD_Region",
    "AD_Area",
    "AD_City",
    "AD_CityArea",
    "AD_Address",
    "AD_Price",
    "AD_PriceNIS",
    "AD_CostTotal",
    "AD_Notes",
    "AD_Coords",
    "AD_CoordsCheck",
    "app_MoveInDate",
    "app_Neighborhood",
    "app_AddressStreet",
    "app_AddressNumber",
    "app_AddressDescription",
    "app_meter",
    "app_meterInt",
    "app_PropertyTypeIndex",
    "app_Typeindex",
    "app_Rooms",
    "app_BathRooms",
    "app_Floor",
    "app_FloorTotal",
    "app_FloorDescription",
    "app_PaymentsNumber",
    "app_Furniture",
    "app_FurnitureIndex",
    "app_FurnitureHave",
    "app_FlatMatesCount",
    "app_RequiredGenderIndex",
    "app_BarsIndex",
    "app_LiftIndex",
    "app_AirConIndex",
    "app_AirConHave",
    "app_storeroom",
    "app_ParkingIndex",
    "app_ParkingHave",
    "app_LocationIndex",
    "app_BalconyIndex",
    "app_BalconeCount",
    "app_BalconyHave",
    "app_SmokingIndex",
    "app_RenovatedIndex",
    "app_TypeProperty",
    "app_AirDirection",
    "app_Status",
    "app_RentTime",
    "app_Partners",
    "app_Animal",
    "app_PartnerSex",
    "app_handicapped",
    "app_Mamad",
    "app_SunBalcone",
    "app_Arnona",
    "app_Kosher",
    "app_Entrance",
    "app_ExtendOption",
    "app_MoveInDateDT",
    "app_IsKones",
    "app_LastServeDate",
    "app_Appraiser",
    "app_IsRealtor",
    "car_Maker",
    "car_Model",
    "car_Color",
    "car_GearFull",
    "car_SubModel",
    "car_Engine",
    "car_Hand",
    "car_Year",
    "car_gear",
    "car_owner",
    "car_PreviousOwner",
    "car_Doors",
    "car_km",
    "AD_Addition",
    "car_AirCon",
    "car_Volume",
    "car_NextTest",
    "car_Accessory",
    "car_AcceptTrade",
    "car_ICarId",
    "car_ICar_PastModel",
    "car_ElectricWindows",
    "car_GPS",
    "car_DVD",
    "car_ABS",
    "car_Conditioner",
    "car_Sunroof",
    "car_Airbags",
    "car_AlloyWheels",
    "yad2_Category",
    "yad2_Product",
    "yad2_Description",
    "yad2_NameProduct",
    "yad2_Operation",
    "yad2_SubCategory",
    "yad2_Maker",
    "Yad2_Status",
    "Yad2_AcceptTrade",
    "anim_Age",
    "anim_Gender",
    "anim_Association",
    "anim_Neutered",
    "anim_Type",
    "anim_Breed",
    "anim_Hours",
    "anim_Immuned",
    "anim_ImmuneDetails",
    "req_Range",
    "req_Role",
    "req_Notes",
    "req_JobRank",
    "req_CompanyName",
    "req_CompanyDetails",
    "req_CompanyRequirement",
    "req_CompanyLogo",
    "AD_Test"
);

$production_fields_types = array(
    "POST_ID" => 'int',
    "cDate" => 'datetime',
    "uDate" => 'datetime',
    "fDate" => 'datetime',
    "dDate" => 'datetime',
    "eDate" => 'datetime',
    "AD_Site" => 'int',
    "AD_Title" => 'text',
    "AD_Section" => 'int',
    "AD_KEY" => 'text',
    "AD_Status" => 'int',
    "AD_UserId" => 'text',
    "AD_Random" => 'int',
    "AD_ContactLink" => 'text',
    "Ad_Link" => 'text',
    "pictureHave" => 'int',
    "pictureFromIcar" => 'int',
    "PicturesString" => 'text',
    "videoHave" => 'int',
    "AD_Phone1" => 'text',
    "AD_Phone2" => 'text',
    "AD_ContactName1" => 'text',
    "AD_ContactEmail" => 'text',
    "AD_ContactCity" => 'text',
    "AD_ContactName2" => 'text',
    "Ad_Fax" => 'text',
    "AD_WebSite" => 'text',
    "AD_ContactAddress" => 'text',
    "AD_PostDate" => 'text',
    "AD_UpdateDate" => 'text',
    "AD_Region" => 'text',
    "AD_Area" => 'text',
    "AD_City" => 'text',
    "AD_CityArea" => 'text',
    "AD_Address" => 'text',
    "AD_Price" => 'int',
    "AD_PriceNIS" => 'int',
    "AD_CostTotal" => 'int',
    "AD_Notes" => 'text',
    "AD_Coords" => 'text',
    "AD_CoordsCheck" => 'int',
    "app_MoveInDate" => 'text',
    "app_Neighborhood" => 'text',
    "app_AddressStreet" => 'text',
    "app_AddressNumber" => 'text',
    "app_AddressDescription" => 'text',
    "app_meter" => 'text',
    "app_meterInt" => 'int',
    "app_PropertyTypeIndex" => 'text',
    "app_Typeindex" => 'text',
    "app_Rooms" => 'text',
    "app_BathRooms" => 'int',
    "app_Floor" => 'text',
    "app_FloorTotal" => 'text',
    "app_FloorDescription" => 'text',
    "app_PaymentsNumber" => 'text',
    "app_Furniture" => 'text',
    "app_FurnitureIndex" => 'text',
    "app_FurnitureHave" => 'text',
    "app_FlatMatesCount" => 'text',
    "app_RequiredGenderIndex" => 'text',
    "app_BarsIndex" => 'text',
    "app_LiftIndex" => 'text',
    "app_AirConIndex" => 'text',
    "app_AirConHave" => 'text',
    "app_storeroom" => 'text',
    "app_ParkingIndex" => 'text',
    "app_ParkingHave" => 'text',
    "app_LocationIndex" => 'text',
    "app_BalconyIndex" => 'text',
    "app_BalconeCount" => 'int',
    "app_BalconyHave" => 'text',
    "app_SmokingIndex" => 'text',
    "app_RenovatedIndex" => 'text',
    "app_TypeProperty" => 'text',
    "app_AirDirection" => 'text',
    "app_Status" => 'text',
    "app_RentTime" => 'text',
    "app_Partners" => 'text',
    "app_Animal" => 'text',
    "app_PartnerSex" => 'text',
    "app_handicapped" => 'text',
    "app_Mamad" => 'text',
    "app_SunBalcone" => 'text',
    "app_Arnona" => 'text',
    "app_Kosher" => 'text',
    "app_Entrance" => 'text',
    "app_ExtendOption" => 'text',
    "app_MoveInDateDT" => 'datetime',
    "app_IsKones" => 'int',
    "app_LastServeDate" => 'datetime',
    "app_Appraiser" => 'text',
    "app_IsRealtor" => 'int',
    "car_Maker" => 'text',
    "car_Model" => 'text',
    "car_Color" => 'text',
    "car_GearFull" => 'text',
    "car_SubModel" => 'text',
    "car_Engine" => 'text',
    "car_Hand" => 'text',
    "car_Year" => 'int',
    "car_gear" => 'text',
    "car_owner" => 'text',
    "car_PreviousOwner=>'text'",
    "car_Doors" => 'text',
    "car_km" => 'float',
    "AD_Addition" => 'text',
    "car_AirCon" => 'text',
    "car_Volume" => 'int',
    "car_NextTest" => 'text',
    "car_Accessory" => 'text',
    "car_AcceptTrade" => 'text',
    "car_ICarId" => 'int',
    "car_ICar_PastModel" => 'int',
    "car_ElectricWindows" => 'text',
    "car_GPS" => 'text',
    "car_DVD" => 'text',
    "car_ABS" => 'text',
    "car_Conditioner" => 'text',
    "car_Sunroof" => 'text',
    "car_Airbags" => 'text',
    "car_AlloyWheels" => 'text',
    "yad2_Category" => 'text',
    "yad2_Product" => 'text',
    "yad2_Description" => 'text',
    "yad2_NameProduct" => 'text',
    "yad2_Operation" => 'text',
    "yad2_SubCategory" => 'text',
    "yad2_Maker" => 'text',
    "Yad2_Status" => 'text',
    "Yad2_AcceptTrade" => 'text',
    "anim_Age" => 'text',
    "anim_Gender" => 'text',
    "anim_Association" => 'text',
    "anim_Neutered" => 'text',
    "anim_Type" => 'text',
    "anim_Breed" => 'text',
    "anim_Hours" => 'text',
    "anim_Immuned" => 'text',
    "anim_ImmuneDetails" => 'text',
    "req_Range" => 'text',
    "req_Role" => 'text',
    "req_Notes" => 'text',
    "req_JobRank" => 'text',
    "req_CompanyName" => 'text',
    "req_CompanyDetails" => 'text',
    "req_CompanyRequirement" => 'text',
    "req_CompanyLogo" => 'text',
    "AD_Test" => 'int'
);

$images_fields = array(
    "AD_Key",
    "cDate",
    "Ad_Site",
    "Ad_Section",
    "ImagePath",
    "ImageName"
);

$images_fields_types = array(
    "AD_Key" => "int",
    "cDate" => "datetime",
    "Ad_Site" => "int",
    "Ad_Section" => "int",
    "ImagePath" => "text",
    "ImageName" => "text"
);

$delete_fields = array(
    "SiteId",
    "SectionId",
    "cDate",
    "AdKey"
);

$delete_fields_types = array(
    "SiteId" => "int",
    "SectionId" => "int",
    "cDate" => "datetime",
    "AdKey" => "int"
);
?>
